using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ShopEZ_OrderService.Models
{
    public class Order
    {
        // Primary key — auto generated by EF Core
        [Key]
        public int OrderId { get; set; }

        // UserId from JWT token — identifies which user placed the order
        [Required(ErrorMessage = "UserId is required")]
        [Range(1, int.MaxValue, ErrorMessage = "UserId must be greater than 0")]
        public int UserId { get; set; }

        // Order date — set automatically when order is created
        [Required]
        public DateTime OrderDate { get; set; }

        // Total amount — calculated from all order items
        [Required]
        [Range(0.01, (double)decimal.MaxValue, ErrorMessage = "TotalAmount must be greater than 0")]
        [Column(TypeName = "decimal(18,2)")]
        public decimal TotalAmount { get; set; }


        // Soft delete flag — true means order is cancelled
        public bool IsCancelled { get; set; } = false;

        // Navigation property — one order has many order items
        public ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
    }

    public class OrderItem
    {
        // Primary key — auto generated by EF Core
        [Key]
        public int OrderItemId { get; set; }

        // Foreign key — links to Order table
        [Required(ErrorMessage = "OrderId is required")]
        public int OrderId { get; set; }

        // ProductId from ProductService
        [Required(ErrorMessage = "ProductId is required")]
        [Range(1, int.MaxValue, ErrorMessage = "ProductId must be greater than 0")]
        public int ProductId { get; set; }

        // Product name — stored directly to avoid cross-service joins
        [Required(ErrorMessage = "Product name is required")]
        [MaxLength(200, ErrorMessage = "Product name cannot exceed 200 characters")]
        public string ProductName { get; set; } = string.Empty;

        // Quantity ordered
        [Required(ErrorMessage = "Quantity is required")]
        [Range(1, int.MaxValue, ErrorMessage = "Quantity must be at least 1")]
        public int Quantity { get; set; }

        // Price at time of order — stored to preserve historical price
        [Required(ErrorMessage = "Price is required")]
        [Range(0.01, (double)decimal.MaxValue, ErrorMessage = "Price must be greater than 0")]
        [Column(TypeName = "decimal(18,2)")]
        public decimal Price { get; set; }

        public string? ImageUrl { get; set; }


        // Navigation property — links back to Order
        public Order? Order { get; set; }
    }
}
