
--The regional manager wants to analyze total sales generated by each store.

USE HandsOn;

CREATE TABLE Stores (
    store_id INT PRIMARY KEY,
    store_name VARCHAR(50)
);

CREATE TABLE Orders1 (
    order_id INT PRIMARY KEY,
    store_id INT,
    order_status INT,
    FOREIGN KEY (store_id) REFERENCES Stores(store_id)
);

CREATE TABLE Order_Items (
    item_id INT PRIMARY KEY,
    order_id INT,
    quantity INT,
    list_price DECIMAL(10,2),
    discount DECIMAL(4,2),
    FOREIGN KEY (order_id) REFERENCES Orders(order_id)
);

INSERT INTO Stores VALUES
	(1, 'Hyderabad Store'),
	(2, 'Chennai Store'),
	(3, 'Bangalore Store');

INSERT INTO Orders1 VALUES
	(101, 1, 4),
	(102, 2, 4),
	(103, 3, 1),
	(104, 1, 4);

INSERT INTO Order_Items VALUES
	(1, 101, 2, 500, 0.10),
	(2, 101, 1, 700, 0.05),
	(3, 102, 3, 400, 0.00),
	(4, 104, 2, 800, 0.10),
	(5, 103, 1, 600, 0.05);
	 

	 SELECT * FROM Stores;
	 SELECT * FROM Orders1;
	 SELECT * FROM Order_Items;
--1. Display store_name and total sales amount.
--2. Calculate total sales using (quantity * list_price * (1 - discount)).
--3. Include only completed orders (order_status = 4).
--4. Group results by store_name.
--5. Sort total sales in descending order.

SELECT s.store_name,SUM(oi.quantity* oi.list_price *(1- oi.discount)) as Total_Sale
FROM Stores s
JOIN Orders1 o ON s.store_id=o.store_id
JOIN Order_Items oi ON o.order_id=oi.order_id
WHERE o.order_status=4
GROUP BY s.store_name
ORDER BY Total_Sale DESC;
